services:
  app:
    image: ghcr.io/jhae-de/node:18
    container_name: ${COMPOSE_PROJECT_NAME:-project-name}-app
    environment:
      HISTFILE: /home/user/workspace/.bash_history
    working_dir: /home/user/workspace
    volumes:
      - ./:/home/user/workspace
    stdin_open: true
    tty: true
