name: Analyze
run-name: Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: jhae-de/jhae-de/.github/workflows/node-project-lint.yaml@main
    with:
      node-version: 18

  test:
    name: Test
    uses: jhae-de/jhae-de/.github/workflows/node-project-test.yaml@main
    with:
      node-version: 18
      upload-coverage: true
