name: Publish
run-name: Release ${{ github.ref_name }}

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    uses: jhae-de/jhae-de/.github/workflows/node-package-publish.yaml@main
    with:
      node-version: 18
    secrets:
      node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
